export default {
    productivity: "Productivity allows you to compare the station's cycle time with the desired station's cycle time for each specific product. Click the gear icon to change what the desired cycle time should be for each product.",
    productivitySettings: "Configure the desired takt time for this product at this station.<br/><br/><b>Process Takt:</b> Compares your production rate to the takt time set over all the stations in this process. This takt time can be configured in the Process Statistics page by dragging the 'Takt' line on the balance graph.<br/><b>Station Takt:</b> Compares the production rate against a takt time that is specific for this product at this station only.<br/><BLOCKQUOTE style='margin-left: 40px'><b>Auto:</b> Compares the production rate to the historical all-time production rate of this product at this station.<br/><b>Manual:</b> Set a production rate to compare the actual production rate to.</BLOCKQUOTE>",
    oee: "Overall Equipment Effectiveness (OEE) is the measure of actual vs. theoretical maximum throughput. This is given by the product of availability, performance, and quality. Click on the gears to specify the theoretical minimum cycle time number of parts for this station.",
    cycleTime: "Cycle time is the measure of (active working) time it takes to produce a single part at this station. This is calculated based on the 'Start' and 'Stop' time for each lot that has moved from this station and the quantity that was moved.",
    throughput: "Throughput is the total number of parts that have passed through this station over the selected date range. Total throughput is broken down by product group. Turn individual lines on and off by clicking on them in the legend. ",
    wip: "Work in Progress (WIP) is the total amount of product sitting at this station over time. WIP is separated by product group with a 'Total' measurement as well. You can toggle lines on this graph by clicking them in the legend.",
    stationReports: "Station reports are triggered by the dashboard operators to indicate events such as machine malfunctions, defects, lack of consumables, and more. Define custom report buttons on the dashboard view of each station.",
    stationReportsPie: "A breakdown of the number of occurances of each report event.",
    processesPie: "A breakdown of the quantity of moved parts by the process they belonged to",
    productGroupPie: "A breakdown of the quantity of moved parts by the product group they belonged to.",
    operatorsPie: "A breakdown of the quantity of moved parts by the operator that moved them.",
    toStationPie: "A breakdown of the quantity of moved parts by the station they were moved to.",
    machineUtilization: "A measure of the utilization of this station: the ratio of total working seconds at this station and the total available working seconds which is based on the shift settings defined in the settings tab. Total working seconds is calculated based on the time a worker was active in a lot (versus looking at the list of lots at the station).",
    valueCreatingTime: "A measure of the relative amount of time a lot was being activly worked on versus the time it spent sitting idle at this station. The active working seconds of this lot is based on the time a worker was active in a lot (versus looking at the list of lots at the station)."
}