projects:
  alpha-cdk-optio-appsync-api:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/schema.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-2
        apiId: dhmlpwwr5rfb7fg6r4hcevzbee
        maxDepth: 2
extensions:
  amplify:
    version: 3
