export const ADD_TASK_ALERT_TYPE = {
	TASK_EXISTS: "TASK_EXISTS",
	TASK_ADDED: "TASK_ADDED",
	ADDING: "ADDING",
	REPORT_SENT: "REPORT_SENT"
}

export const PAGES = {
	DASHBOARDS: "Dashboards",
	EDITING: "Editing",
	DASHBOARD: "Dashboard"
}