export const ADD_TASK_ALERT_TYPE = {
	TASK_EXISTS: "TASK_EXISTS",
	TASK_ADDED: "TASK_ADDED",
	ADDING: "ADDING",
	REPORT_SEND_SUCCESS: "REPORT_SEND_SUCCESS",
	REPORT_SEND_FAILURE: "REPORT_SEND_FAILURE",
	KICK_OFF_SUCCESS: "KICK_OFF_SUCCESS",
	KICK_OFF_FAILURE: "KICK_OFF_FAILURE",
	FINISH_SUCCESS: "FINISH_SUCCESS",
	FINISH_FAILURE: "FINISH_FAILURE",
}

export const PAGES = {
	DASHBOARDS: "Dashboards",
	EDITING: "Editing",
	DASHBOARD: "Dashboard"
}

export const DASHBOARD_BUTTON_COLORS = ['#FF4B4B', '#56d5f5', '#50de76', '#f2ae41', '#c7a0fa']