export const GET_REFRESH_TOKEN = 'GET_REFRESH_TOKEN'
export const GET_REFRESH_TOKEN_STARTED = 'GET_REFRESH_TOKEN_STARTED'
export const GET_REFRESH_TOKEN_SUCCESS = 'GET_REFRESH_TOKEN_SUCCESS'
export const GET_REFRESH_TOKEN_FAILURE = 'GET_REFRESH_TOKEN_FAILURE'

export const POST_REFRESH_TOKEN = 'POST_REFRESH_TOKEN'
export const POST_REFRESH_TOKEN_STARTED = 'POST_REFRESH_TOKEN_STARTED'
export const POST_REFRESH_TOKEN_SUCCESS = 'POST_REFRESH_TOKEN_SUCCESS'
export const POST_REFRESH_TOKEN_FAILURE = 'POST_REFRESH_TOKEN_FAILURE'