export const GET_DASHBOARDS = 'GET_DASHBOARDS'
export const GET_DASHBOARDS_STARTED = 'GET_DASHBOARDS_STARTED'
export const GET_DASHBOARDS_SUCCESS = 'GET_DASHBOARDS_SUCCESS'
export const GET_DASHBOARDS_FAILURE = 'GET_DASHBOARDS_FAILURE'

export const POST_DASHBOARDS = 'POST_DASHBOARDS'
export const POST_DASHBOARDS_STARTED = 'POST_DASHBOARDS_STARTED'
export const POST_DASHBOARDS_SUCCESS = 'POST_DASHBOARDS_SUCCESS'
export const POST_DASHBOARDS_FAILURE = 'POST_DASHBOARDS_FAILURE'

export const PUT_DASHBOARDS = 'PUT_DASHBOARDS'
export const PUT_DASHBOARDS_STARTED = 'PUT_DASHBOARDS_STARTED'
export const PUT_DASHBOARDS_SUCCESS = 'PUT_DASHBOARDS_SUCCESS'
export const PUT_DASHBOARDS_FAILURE = 'PUT_DASHBOARDS_FAILURE'

export const DELETE_DASHBOARDS = 'DELETE_DASHBOARDS'
export const DELETE_DASHBOARDS_STARTED = 'DELETE_DASHBOARDS_STARTED'
export const DELETE_DASHBOARDS_SUCCESS = 'DELETE_DASHBOARDS_SUCCESS'
export const DELETE_DASHBOARDS_FAILURE = 'DELETE_DASHBOARDS_FAILURE'
