export const GET_DASHBOARDS = "GET_DASHBOARDS";
export const GET_DASHBOARDS_STARTED = "GET_DASHBOARDS_STARTED";
export const GET_DASHBOARDS_SUCCESS = "GET_DASHBOARDS_SUCCESS";
export const GET_DASHBOARDS_FAILURE = "GET_DASHBOARDS_FAILURE";

export const POST_DASHBOARD = "POST_DASHBOARD";
export const POST_DASHBOARD_STARTED = "POST_DASHBOARD_STARTED";
export const POST_DASHBOARD_SUCCESS = "POST_DASHBOARD_SUCCESS";
export const POST_DASHBOARD_FAILURE = "POST_DASHBOARD_FAILURE";

export const PUT_DASHBOARD = "PUT_DASHBOARD";
export const PUT_DASHBOARD_STARTED = "PUT_DASHBOARD_STARTED";
export const PUT_DASHBOARD_SUCCESS = "PUT_DASHBOARD_SUCCESS";
export const PUT_DASHBOARD_FAILURE = "PUT_DASHBOARD_FAILURE";

export const DELETE_DASHBOARD = "DELETE_DASHBOARD";
export const DELETE_DASHBOARD_STARTED = "DELETE_DASHBOARD_STARTED";
export const DELETE_DASHBOARD_SUCCESS = "DELETE_DASHBOARD_SUCCESS";
export const DELETE_DASHBOARD_FAILURE = "DELETE_DASHBOARD_FAILURE";

export const DASHBOARD_OPEN = "DASHBOARD_OPEN";
