export const GET_DEVICES = 'GET_DEVICES'
export const GET_DEVICES_STARTED = 'GET_DEVICES_STARTED'
export const GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS'
export const GET_DEVICES_FAILURE = 'GET_DEVICES_FAILURE'

export const POST_DEVICES = 'POST_DEVICES'
export const POST_DEVICES_STARTED = 'POST_DEVICES_STARTED'
export const POST_DEVICES_SUCCESS = 'POST_DEVICES_SUCCESS'
export const POST_DEVICES_FAILURE = 'POST_DEVICES_FAILURE'

export const PUT_DEVICES = 'PUT_DEVICES'
export const PUT_DEVICES_STARTED = 'PUT_DEVICES_STARTED'
export const PUT_DEVICES_SUCCESS = 'PUT_DEVICES_SUCCESS'
export const PUT_DEVICES_FAILURE = 'PUT_DEVICES_FAILURE'

export const DELETE_DEVICES = 'DELETE_DEVICES'
export const DELETE_DEVICES_STARTED = 'DELETE_DEVICES_STARTED'
export const DELETE_DEVICES_SUCCESS = 'DELETE_DEVICES_SUCCESS'
export const DELETE_DEVICES_FAILURE = 'DELETE_DEVICES_FAILURE'
