export const GET_EVENTS = 'GET_EVENTS'
export const GET_EVENTS_STARTED = 'GET_EVENTS_STARTED'
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE'

export const POST_EVENTS = 'POST_EVENTS'
export const POST_EVENTS_STARTED = 'POST_EVENTS_STARTED'
export const POST_EVENTS_SUCCESS = 'POST_EVENTS_SUCCESS'
export const POST_EVENTS_FAILURE = 'POST_EVENTS_FAILURE'

export const PUT_EVENTS = 'PUT_EVENTS'
export const PUT_EVENTS_STARTED = 'PUT_EVENTS_STARTED'
export const PUT_EVENTS_SUCCESS = 'PUT_EVENTS_SUCCESS'
export const PUT_EVENTS_FAILURE = 'PUT_EVENTS_FAILURE'

export const DELETE_EVENTS = 'DELETE_EVENTS'
export const DELETE_EVENTS_STARTED = 'DELETE_EVENTS_STARTED'
export const DELETE_EVENTS_SUCCESS = 'DELETE_EVENTS_SUCCESS'
export const DELETE_EVENTS_FAILURE = 'DELETE_EVENTS_FAILURE'
