export const GET_IMAGE = 'GET_IMAGE';
export const GET_IMAGE_STARTED = 'GET_IMAGE_STARTED';
export const GET_IMAGE_SUCCESS = 'GET_IMAGE_SUCCESS';
export const GET_IMAGE_FAILURE = 'GET_IMAGE_FAILURE';
