export const SELECT_LOCATION = 'SELECT_LOCATION'
export const DESELECT_LOCATION = 'DESELECT_LOCATION'
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION'
export const SET_SELECTED_LOCATION_COPY = 'SET_SELECTED_LOCATION_COPY'
export const SET_SELECTED_LOCATION_CHILDREN_COPY = 'SET_SELECTED_LOCATION_CHILDREN_COPY'

export const WIDGET_LOADED = 'WIDGET_LOADED'