export const GET_LOGGERS = "GET_LOGGERS";
export const GET_LOGGERS_STARTED = "GET_LOGGERS_STARTED";
export const GET_LOGGERS_SUCCESS = "GET_LOGGERS_SUCCESS";
export const GET_LOGGERS_FAILURE = "GET_LOGGERS_FAILURE";

export const POST_LOGGERS = "POST_LOGGERS";
export const POST_LOGGERS_STARTED = "POST_LOGGERS_STARTED";
export const POST_LOGGERS_SUCCESS = "POST_LOGGERS_SUCCESS";
export const POST_LOGGERS_FAILURE = "POST_LOGGERS_FAILURE";

export const PUT_LOGGERS = "PUT_LOGGERS";
export const PUT_LOGGERS_STARTED = "PUT_LOGGERS_STARTED";
export const PUT_LOGGERS_SUCCESS = "PUT_LOGGERS_SUCCESS";
export const PUT_LOGGERS_FAILURE = "PUT_LOGGERS_FAILURE";

export const DELETE_LOGGERS = "DELETE_LOGGERS";
export const DELETE_LOGGERS_STARTED = "DELETE_LOGGERS_STARTED";
export const DELETE_LOGGERS_SUCCESS = "DELETE_LOGGERS_SUCCESS";
export const DELETE_LOGGERS_FAILURE = "DELETE_LOGGERS_FAILURE";
