export const GET_MAPS = 'GET_MAPS'
export const GET_MAPS_STARTED = 'GET_MAPS_STARTED'
export const GET_MAPS_SUCCESS = 'GET_MAPS_SUCCESS'
export const GET_MAPS_FAILURE = 'GET_MAPS_FAILURE'

export const GET_MAP = 'GET_MAP'
export const GET_MAP_STARTED = 'GET_MAP_STARTED'
export const GET_MAP_SUCCESS = 'GET_MAP_SUCCESS'
export const GET_MAP_FAILURE = 'GET_MAP_FAILURE'

export const SET_MAP_ATTRIBUTES = 'SET_MAP_ATTRIBUTES'
export const SET_CURRENT_MAP = 'SET_CURRENT_MAP'
