export const GET_MODELS = 'GET_MODELS';
export const GET_MODELS_STARTED = 'GET_MODELS_STARTED';
export const GET_MODELS_SUCCESS = 'GET_MODELS_SUCCESS';
export const GET_MODELS_FAILURE = 'GET_MODELS_FAILURE';
