export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const GET_NOTIFICATIONS_STARTED = "GET_NOTIFICATIONS_STARTED";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAILURE = "GET_NOTIFICATIONS_FAILURE";

export const POST_NOTIFICATIONS = "POST_NOTIFICATIONS";
export const POST_NOTIFICATIONS_STARTED = "POST_NOTIFICATIONS_STARTED";
export const POST_NOTIFICATIONS_SUCCESS = "POST_NOTIFICATIONS_SUCCESS";
export const POST_NOTIFICATIONS_FAILURE = "POST_NOTIFICATIONS_FAILURE";

export const PUT_NOTIFICATION = "PUT_NOTIFICATIONS";
export const PUT_NOTIFICATION_STARTED = "PUT_NOTIFICATIONS_STARTED";
export const PUT_NOTIFICATION_SUCCESS = "PUT_NOTIFICATIONS_SUCCESS";
export const PUT_NOTIFICATION_FAILURE = "PUT_NOTIFICATIONS_FAILURE";

export const DELETE_NOTIFICATIONS = "DELETE_NOTIFICATIONS";
export const DELETE_NOTIFICATIONS_STARTED = "DELETE_NOTIFICATIONS_STARTED";
export const DELETE_NOTIFICATIONS_SUCCESS = "DELETE_NOTIFICATIONS_SUCCESS";
export const DELETE_NOTIFICATIONS_FAILURE = "DELETE_NOTIFICATIONS_FAILURE";

export const DELETE_NOTIFICATION = "DELETE_NOTIFICATIONS";
export const DELETE_NOTIFICATION_STARTED = "DELETE_NOTIFICATIONS_STARTED";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATIONS_SUCCESS";
export const DELETE_NOTIFICATION_FAILURE = "DELETE_NOTIFICATIONS_FAILURE";

export const TOGGLE_NOTIFICATION_TASK_QUEUE = "TOGGLE_NOTIFICATION_TASK_QUEUE";
