export const GET_POSES = "GET_POSES";
export const GET_POSES_STARTED = "GET_POSES_STARTED";
export const GET_POSES_SUCCESS = "GET_POSES_SUCCESS";
export const GET_POSES_FAILURE = "GET_POSES_FAILURE";

export const GET_POSE = "GET_POSE";
export const GET_POSE_STARTED = "GET_POSE_STARTED";
export const GET_POSE_SUCCESS = "GET_POSE_SUCCESS";
export const GET_POSE_FAILURE = "GET_POSE_FAILURE";
