export const GET_POSITIONS_STARTED = 'GET_POSITIONS_STARTED'
export const GET_POSITIONS_SUCCESS = 'GET_POSITIONS_SUCCESS'
export const GET_POSITIONS_FAILURE = 'GET_POSITIONS_FAILURE'

export const GET_POSITION_STARTED = 'GET_POSITION_STARTED'
export const GET_POSITION_SUCCESS = 'GET_POSITION_SUCCESS'
export const GET_POSITION_FAILURE = 'GET_POSITION_FAILURE'

export const POST_POSITION_STARTED = 'POST_POSITION_STARTED'
export const POST_POSITION_SUCCESS = 'POST_POSITION_SUCCESS'
export const POST_POSITION_FAILURE = 'POST_POSITION_FAILURE'

export const PUT_POSITION_STARTED = 'PUT_POSITION_STARTED'
export const PUT_POSITION_SUCCESS = 'PUT_POSITION_SUCCESS'
export const PUT_POSITION_FAILURE = 'PUT_POSITION_FAILURE'

export const DELETE_POSITION_STARTED = 'DELETE_POSITION_STARTED'
export const DELETE_POSITION_SUCCESS = 'DELETE_POSITION_SUCCESS'
export const DELETE_POSITION_FAILURE = 'DELETE_POSITION_FAILURE'

export const ADD_POSITION = 'ADD_POSITION'
export const UPDATE_POSITION = 'UPDATE_POSITION'
export const UPDATE_POSITIONS = 'UPDATE_POSITIONS'
export const REMOVE_POSITION = 'REMOVE_POSITION'
export const SET_POSITION_ATTRIBUTES = 'SET_POSITION_ATTRIBUTES'