export const GET_SETTINGS = 'GET_SETTINGS'
export const GET_SETTINGS_STARTED = 'GET_SETTINGS_STARTED'
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS'
export const GET_SETTINGS_FAILURE = 'GET_SETTINGS_FAILURE'

export const POST_SETTINGS = 'POST_SETTINGS'
export const POST_SETTINGS_STARTED = 'POST_SETTINGS_STARTED'
export const POST_SETTINGS_SUCCESS = 'POST_SETTINGS_SUCCESS'
export const POST_SETTINGS_FAILURE = 'POST_SETTINGS_FAILURE'

export const PUT_SETTINGS = 'PUT_SETTINGS'
export const PUT_SETTINGS_STARTED = 'PUT_SETTINGS_STARTED'
export const PUT_SETTINGS_SUCCESS = 'PUT_SETTINGS_SUCCESS'
export const PUT_SETTINGS_FAILURE = 'PUT_SETTINGS_FAILURE'

export const DELETE_SETTINGS = 'DELETE_SETTINGS'
export const DELETE_SETTINGS_STARTED = 'DELETE_SETTINGS_STARTED'
export const DELETE_SETTINGS_SUCCESS = 'DELETE_SETTINGS_SUCCESS'
export const DELETE_SETTINGS_FAILURE = 'DELETE_SETTINGS_FAILURE'

export const POST_TASK_QUEUE = 'POST_TASK_QUEUE'
export const POST_TASK_QUEUE_STARTED = 'POST_TASK_QUEUE_STARTED'
export const POST_TASK_QUEUE_SUCCESS = 'POST_TASK_QUEUE_SUCCESS'
export const POST_TASK_QUEUE_FAILURE = 'POST_TASK_QUEUE_FAILURE'