export const GET_SKILLS = "GET_SKILLS";
export const GET_SKILLS_STARTED = "GET_SKILLS_STARTED";
export const GET_SKILLS_SUCCESS = "GET_SKILLS_SUCCESS";
export const GET_SKILLS_FAILURE = "GET_SKILLS_FAILURE";

export const POST_SKILLS = "POST_SKILLS";
export const POST_SKILLS_STARTED = "POST_SKILLS_STARTED";
export const POST_SKILLS_SUCCESS = "POST_SKILLS_SUCCESS";
export const POST_SKILLS_FAILURE = "POST_SKILLS_FAILURE";

export const PUT_SKILLS = "PUT_SKILLS";
export const PUT_SKILLS_STARTED = "PUT_SKILLS_STARTED";
export const PUT_SKILLS_SUCCESS = "PUT_SKILLS_SUCCESS";
export const PUT_SKILLS_FAILURE = "PUT_SKILLS_FAILURE";

export const DELETE_SKILLS = "DELETE_SKILLS";
export const DELETE_SKILLS_STARTED = "DELETE_SKILLS_STARTED";
export const DELETE_SKILLS_SUCCESS = "DELETE_SKILLS_SUCCESS";
export const DELETE_SKILLS_FAILURE = "DELETE_SKILLS_FAILURE";
