export const GET_SKILL_TEMPLATES = "GET_SKILL_TEMPLATES";
export const GET_SKILL_TEMPLATES_STARTED = "GET_SKILL_TEMPLATES_STARTED";
export const GET_SKILL_TEMPLATES_SUCCESS = "GET_SKILL_TEMPLATES_SUCCESS";
export const GET_SKILL_TEMPLATES_FAILURE = "GET_SKILL_TEMPLATES_FAILURE";
