export const GET_STATIONS_STARTED = 'GET_STATIONS_STARTED'
export const GET_STATIONS_SUCCESS = 'GET_STATIONS_SUCCESS'
export const GET_STATIONS_FAILURE = 'GET_STATIONS_FAILURE'

export const POST_STATION_STARTED = 'POST_STATION_STARTED'
export const POST_STATION_SUCCESS = 'POST_STATION_SUCCESS'
export const POST_STATION_FAILURE = 'POST_STATION_FAILURE'

export const PUT_STATION_STARTED = 'PUT_STATION_STARTED'
export const PUT_STATION_SUCCESS = 'PUT_STATION_SUCCESS'
export const PUT_STATION_FAILURE = 'PUT_STATION_FAILURE'

export const DELETE_STATION_STARTED = 'DELETE_STATION_STARTED'
export const DELETE_STATION_SUCCESS = 'DELETE_STATION_SUCCESS'
export const DELETE_STATION_FAILURE = 'DELETE_STATION_FAILURE'

export const UPDATE_STATION_CYCLE_TIME_STARTED = 'UPDATE_STATION_CYCLE_TIME_STARTED'
export const UPDATE_STATION_CYCLE_TIME_SUCCESS = 'UPDATE_STATION_CYCLE_TIME_SUCCESS'
export const UPDATE_STATION_CYCLE_TIME_FAILURE = 'UPDATE_STATION_CYCLE_TIME_FAILURE'

export const ADD_STATION = 'ADD_STATION'
export const UPDATE_STATION = 'UPDATE_STATION'
export const UPDATE_STATIONS = 'UPDATE_STATIONS'
export const REMOVE_STATION = 'REMOVE_STATION'
export const EDITING_STATION = 'EDITING_STATION'
export const SET_STATION_ATTRIBUTES = 'SET_STATION_ATTRIBUTES'
export const SET_SELECTED_STATION = 'SET_SELECTED_STATION'