export const GET_TASK_QUEUE = 'GET_TASK_QUEUE'
export const GET_TASK_QUEUE_STARTED = 'GET_TASK_QUEUE_STARTED'
export const GET_TASK_QUEUE_SUCCESS = 'GET_TASK_QUEUE_SUCCESS'
export const GET_TASK_QUEUE_FAILURE = 'GET_TASK_QUEUE_FAILURE'

export const GET_TASK_QUEUE_ITEM = 'GET_TASK_QUEUE_ITEM'
export const GET_TASK_QUEUE_ITEM_STARTED = 'GET_TASK_QUEUE_ITEM_STARTED'
export const GET_TASK_QUEUE_ITEM_SUCCESS = 'GET_TASK_QUEUE_ITEM_SUCCESS'
export const GET_TASK_QUEUE_ITEM_FAILURE = 'GET_TASK_QUEUE_ITEM_FAILURE'

export const POST_TASK_QUEUE = 'POST_TASK_QUEUE'
export const POST_TASK_QUEUE_STARTED = 'POST_TASK_QUEUE_STARTED'
export const POST_TASK_QUEUE_SUCCESS = 'POST_TASK_QUEUE_SUCCESS'
export const POST_TASK_QUEUE_FAILURE = 'POST_TASK_QUEUE_FAILURE'

export const DELETE_TASK_QUEUE = 'DELETE_TASK_QUEUE'
export const DELETE_TASK_QUEUE_STARTED = 'DELETE_TASK_QUEUE_STARTED'
export const DELETE_TASK_QUEUE_SUCCESS = 'DELETE_TASK_QUEUE_SUCCESS'
export const DELETE_TASK_QUEUE_FAILURE = 'DELETE_TASK_QUEUE_FAILURE'

export const TASK_QUEUE = 'TASK_QUEUE'
export const TASK_QUEUE_ALL = 'TASK_QUEUE_ALL'
export const TASK_QUEUE_ITEM = 'TASK_QUEUE_ITEM'
