// TASKS types
export const TASKS = 'TASKS';
export const TASK = 'TASK';

export const ANALYSIS = 'ANALYSIS';

export const GET_TASKS = 'GET_TASKS'
export const GET_TASKS_STARTED = 'GET_TASKS_STARTED'
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE'

export const GET_TASK = 'GET_TASK'
export const GET_TASK_STARTED = 'GET_TASK_STARTED'
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS'
export const GET_TASK_FAILURE = 'GET_TASK_FAILURE'

export const POST_TASK = 'POST_TASK'
export const POST_TASK_STARTED = 'POST_TASK_STARTED'
export const POST_TASK_SUCCESS = 'POST_TASK_SUCCESS'
export const POST_TASK_FAILURE = 'POST_TASK_FAILURE'

export const PUT_TASK = 'PUT_TASK'
export const PUT_TASK_STARTED = 'PUT_TASK_STARTED'
export const PUT_TASK_SUCCESS = 'PUT_TASK_SUCCESS'
export const PUT_TASK_FAILURE = 'PUT_TASK_FAILURE'

export const DELETE_TASK = 'DELETE_TASK'
export const DELETE_TASK_STARTED = 'DELETE_TASK_STARTED'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE'

export const ADD_TASK = 'ADD_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const UPDATE_TASKS = 'UPDATE_TASKS'
export const REMOVE_TASK = 'REMOVE_TASK'
export const SET_TASK_ATTRIBUTES = 'SET_TASK_ATTRIBUTES'
export const VALIDATE_TASK = 'VALIDATE_TASK'
export const SELECT_TASK = 'SELECT_TASK'
export const SET_SELECTED_TASK = 'SET_SELECTED_TASK'
export const DESELECT_TASK = 'DESELECT_TASK'
export const EDITING_TASK = 'EDITING_TASK'
