export const GET_TOUCH_EVENTS = 'GET_TOUCH_EVENTS'
export const GET_TOUCH_EVENTS_STARTED = 'GET_TOUCH_EVENTS_STARTED'
export const GET_TOUCH_EVENTS_SUCCESS = 'GET_TOUCH_EVENTS_SUCCESS'
export const GET_TOUCH_EVENTS_FAILURE = 'GET_TOUCH_EVENTS_FAILURE'

export const GET_LOT_TOUCH_EVENTS = 'GET_LOT_TOUCH_EVENTS'
export const GET_LOT_TOUCH_EVENTS_STARTED = 'GET_LOT_TOUCH_EVENTS_STARTED'
export const GET_LOT_TOUCH_EVENTS_SUCCESS = 'GET_LOT_TOUCH_EVENTS_SUCCESS'
export const GET_LOT_TOUCH_EVENTS_FAILURE = 'GET_LOT_TOUCH_EVENTS_FAILURE'

export const POST_TOUCH_EVENTS = 'POST_TOUCH_EVENTS'
export const POST_TOUCH_EVENTS_STARTED = 'POST_TOUCH_EVENTS_STARTED'
export const POST_TOUCH_EVENTS_SUCCESS = 'POST_TOUCH_EVENTS_SUCCESS'
export const POST_TOUCH_EVENTS_FAILURE = 'POST_TOUCH_EVENTS_FAILURE'

export const PUT_TOUCH_EVENTS = 'PUT_TOUCH_EVENTS'
export const PUT_TOUCH_EVENTS_STARTED = 'PUT_TOUCH_EVENTS_STARTED'
export const PUT_TOUCH_EVENTS_SUCCESS = 'PUT_TOUCH_EVENTS_SUCCESS'
export const PUT_TOUCH_EVENTS_FAILURE = 'PUT_TOUCH_EVENTS_FAILURE'

export const DELETE_TOUCH_EVENTS = 'DELETE_TOUCH_EVENTS'
export const DELETE_TOUCH_EVENTS_STARTED = 'DELETE_TOUCH_EVENTS_STARTED'
export const DELETE_TOUCH_EVENTS_SUCCESS = 'DELETE_TOUCH_EVENTS_SUCCESS'
export const DELETE_TOUCH_EVENTS_FAILURE = 'DELETE_TOUCH_EVENTS_FAILURE'

export const OPEN_TOUCH_EVENT = 'OPEN_TOUCH_EVENT'
export const OPEN_TOUCH_EVENT_STARTED = 'OPEN_TOUCH_EVENT_STARTED'
export const OPEN_TOUCH_EVENT_SUCCESS = 'OPEN_TOUCH_EVENT_SUCCESS'
export const OPEN_TOUCH_EVENT_FAILURE = 'OPEN_TOUCH_EVENT_FAILURE'

export const CLOSE_TOUCH_EVENT = 'CLOSE_TOUCH_EVENT'
export const CLOSE_TOUCH_EVENT_STARTED = 'CLOSE_TOUCH_EVENT_STARTED'
export const CLOSE_TOUCH_EVENT_SUCCESS = 'CLOSE_TOUCH_EVENT_SUCCESS'
export const CLOSE_TOUCH_EVENT_FAILURE = 'CLOSE_TOUCH_EVENT_FAILURE'

export const GET_OPEN_TOUCH_EVENTS = 'GET_OPEN_TOUCH_EVENTS'
export const GET_OPEN_TOUCH_EVENTS_STARTED = 'GET_OPEN_TOUCH_EVENTS_STARTED'
export const GET_OPEN_TOUCH_EVENTS_SUCCESS = 'GET_OPEN_TOUCH_EVENTS_SUCCESS'
export const GET_OPEN_TOUCH_EVENTS_FAILURE = 'GET_OPEN_TOUCH_EVENTS_FAILURE'

export const GET_OPEN_STATION_TOUCH_EVENTS = 'GET_OPEN_STATION_TOUCH_EVENTS'
export const GET_OPEN_STATION_TOUCH_EVENTS_STARTED = 'GET_OPEN_STATION_TOUCH_EVENTS_STARTED'
export const GET_OPEN_STATION_TOUCH_EVENTS_SUCCESS = 'GET_OPEN_STATION_TOUCH_EVENTS_SUCCESS'
export const GET_OPEN_STATION_TOUCH_EVENTS_FAILURE = 'GET_OPEN_STATION_TOUCH_EVENTS_FAILURE'