export const GET_TOUCH_EVENTS = 'GET_TOUCH_EVENTS'
export const GET_TOUCH_EVENTS_STARTED = 'GET_TOUCH_EVENTS_STARTED'
export const GET_TOUCH_EVENTS_SUCCESS = 'GET_TOUCH_EVENTS_SUCCESS'
export const GET_TOUCH_EVENTS_FAILURE = 'GET_TOUCH_EVENTS_FAILURE'

export const GET_LOT_TOUCH_EVENTS = 'GET_LOT_TOUCH_EVENTS'
export const GET_LOT_TOUCH_EVENTS_STARTED = 'GET_LOT_TOUCH_EVENTS_STARTED'
export const GET_LOT_TOUCH_EVENTS_SUCCESS = 'GET_LOT_TOUCH_EVENTS_SUCCESS'
export const GET_LOT_TOUCH_EVENTS_FAILURE = 'GET_LOT_TOUCH_EVENTS_FAILURE'

export const POST_TOUCH_EVENTS = 'POST_TOUCH_EVENTS'
export const POST_TOUCH_EVENTS_STARTED = 'POST_TOUCH_EVENTS_STARTED'
export const POST_TOUCH_EVENTS_SUCCESS = 'POST_TOUCH_EVENTS_SUCCESS'
export const POST_TOUCH_EVENTS_FAILURE = 'POST_TOUCH_EVENTS_FAILURE'

export const PUT_TOUCH_EVENTS = 'PUT_TOUCH_EVENTS'
export const PUT_TOUCH_EVENTS_STARTED = 'PUT_TOUCH_EVENTS_STARTED'
export const PUT_TOUCH_EVENTS_SUCCESS = 'PUT_TOUCH_EVENTS_SUCCESS'
export const PUT_TOUCH_EVENTS_FAILURE = 'PUT_TOUCH_EVENTS_FAILURE'

export const DELETE_TOUCH_EVENTS = 'DELETE_TOUCH_EVENTS'
export const DELETE_TOUCH_EVENTS_STARTED = 'DELETE_TOUCH_EVENTS_STARTED'
export const DELETE_TOUCH_EVENTS_SUCCESS = 'DELETE_TOUCH_EVENTS_SUCCESS'
export const DELETE_TOUCH_EVENTS_FAILURE = 'DELETE_TOUCH_EVENTS_FAILURE'
