export const WIDGET_PAGE_LOADED = "WIDGET_PAGE_LOADED";
export const WIDGET_XY_COORDINATES = "WIDGET_XY_COORDINATES";
export const WIDGET_LOADED = "WIDGET_LOADED";
export const HOVER_STATION_INFO = "HOVER_STATION_INFO";
