/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_5MFOsswHz",
    "aws_user_pools_web_client_id": "3ke6d3tcen5pm0fqepj8f6ja6p",
    "oauth": {
        "domain": "optio.auth.us-east-2.amazoncognito.com"
    },
    "aws_appsync_graphqlEndpoint": "https://joaunv2xfna3dmwrw4aeykagcy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
