/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:300786a6-b83d-4dc3-a69e-89884a101410",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wO9LTxqpv",
    "aws_user_pools_web_client_id": "1vv2q5pba26s8t46cfbobai93v",
    "oauth": {}
};


export default awsmobile;
