/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a0ee8145-6d9e-4c8d-910d-6326b9e38e79",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_HdW9xqBHl",
    "aws_user_pools_web_client_id": "509viau1ke48oupulvhr5rnonj",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://gqnfudrgfbgy5drqadncozg54y.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456"
};


export default awsmobile;
